# Generated by Django 4.2.2 on 2023-07-06 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=10)),
                ("academic_scale", models.CharField(max_length=10)),
                ("num_courses", models.PositiveIntegerField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default="default.jpeg", upload_to="users"
                    ),
                ),
                ("country", models.CharField(default="Nigeria", max_length=60)),
                (
                    "level",
                    models.CharField(
                        choices=[("Masters", "Masters"), ("BSc", "BSc")], max_length=30
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
