# Generated by Django 4.2.2 on 2023-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="degree",
        ),
        migrations.AddField(
            model_name="profile",
            name="course_of_study",
            field=models.CharField(
                default="Computer Science", max_length=60, null=True
            ),
        ),
    ]
